### PR TITLE
Fixed a segfault 11 error on macOS

### PR DESCRIPTION
**Pull request by oeed**

### CODE REVIEW

**Comment by Lignum** [comment]
Make that:
```CMake
if(APPLE)
  set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-pagezero_size 10000 -image_base 100000000")
endif()
```
This way, it will only set the flags on macOS and it will also keep existing flags.

**Comment by incinirate** [comment]
@oeed can you confirm that Lignum's solution works?

**Comment by oeed** [comment]
Yep it does @incinirate, thanks @Lignum!

**Comment by incinirate** [comment]
Cool, thanks guys!

**Pull request merged**
