### PR TITLE
[WIP] Custom FS

### PR DESCRIPTION
**Pull request by incinirate**
Haven't written it yet, wondering if it's necessary...

### CODE REVIEW

**Comment by CrazedProgrammer** [comment]
Add custom filesystem support, it would be cool to make for example a RAMfs or network fs :)

**Comment by incinirate** [comment]
Ok, any suggestions on API design?

**Comment by CrazedProgrammer** [comment]
`fs.open(file, mode) fs.list(dir) fs.getAttributes(path) fs.delete(path)` i dont think you need much else

**Comment by incinirate** [comment]
This should be ready to merge now, im so happy

**Pull request merged**
