### PR TITLE
Fix segfault on Linux

### LINKED ISSUE #19: Trouble on Linux
There are some issues with running Riko4 on Linux:
- While building, `SDL2.h` conflicts with `SDL2_gpu.h`. Removing all occurrences of `#include <SDL/SDL2.h>` fixes this, but I don't know if this breaks Windows builds.
- Starting the game immediately causes a segmentation fault:
```
➜  Riko4 git:(master) ✗ ./riko4
ATTENTION: default value of option vblank_mode overridden by environment.
Connected controller 0
Got 2
Riko4 path: '/home/lig/.local/share/riko4/app/'
[1]    6856 segmentation fault (core dumped)  ./riko4
```
GDB output:
```
Thread 1 "riko4" received signal SIGSEGV, Segmentation fault.
0x000000000040c114 in main (argc=1, argv=0x7fffffffdf68) at /home/lig/Projects/Riko4/src/riko.cpp:641
641	    window = SDL_GetWindowFromID(renderer->renderer->current_context_target->context->windowID);
(gdb) p renderer
$1 = (GPU_Target *) 0x7a9d20
(gdb) p renderer->renderer
$2 = (GPU_Renderer *) 0x6917e0
(gdb) p renderer->renderer->current_context_target
$3 = (GPU_Target *) 0x7a9d20
(gdb) p renderer->renderer->current_context_target->context
$4 = (GPU_Context *) 0x10001
(gdb) p renderer->renderer->current_context_target->context->windowID
Cannot access memory at address 0x1000d
(gdb) 
```

### PR DESCRIPTION
**Pull request by Lignum**
This fixes #19. Please test this on Windows before merging, I don't know if the removal of the `#include <SDL2/SDL.h>` directives breaks it.

### CODE REVIEW

**Comment by Lignum** [comment]
Not sure why the build's failing, perhaps travis is using an outdated version of SDL_gpu?

**Comment by incinirate** [comment]
Travis builds sdl_gpu from source when it builds, from the logs it looks like removing the sdl.h includes removed some of the sdl structs.. Thanks for looking into this btw!

**Comment by incinirate** [comment]
Although it is strange considering sdl_gpu.h includes sdl.h... hmm

**Comment by Lignum** [comment]
Well, that is especially odd, since I built it from source as well.

**Comment by incinirate** [comment]
Hmm, all of your changes seem to work on windows as well, very curious why travis is having a fit..

**Comment by incinirate** [comment]
It seems that the missing structs were introduced in SDL 2.0.4, whereas the version of SDL2 that travis uses is 2.0.2, although I am very concerned as to why the travis build was working before 🤔

**Comment by Lignum** [comment]
Hm yes, that is odd. Good to know that shit's not fucked in this PR, though.

**Comment by incinirate** [comment]
Ok, I pushed a commit that should settle travis down, I'm going to merge and see what happens..

**Comment by incinirate** [comment]
Yep, build worked, very strange but thanks so much!

**Pull request merged**
